version: '3'

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    logging:
      driver: "none"

  mongodb:
    image: 'bitnami/mongodb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 27017:27017
    logging:
      driver: "none"

  lute:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        workspace: lute
    command: npx turbo run dev --filter=lute
    ports:
      - ${SERVER_PORT}:80
    restart: always
    volumes:
      - ./packages:/app/packages
      - ./apps/lute:/app/apps/lute
    env_file:
      - .env

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        workspace: dashboard
    command: npx turbo run dev --filter=dashboard
    ports:
      - ${DASHBOARD_PORT}:80
    restart: always
    environment:
      - ENV
      - NEXT_PUBLIC_LUTE_SERVER_URL
      - LUTE_SERVER_URL
      - REDIS_URL
      - PORT=80
      - DASHBOARD_PORT