FROM node:lts-buster-slim AS base
ARG workspace
ENV WORKSPACE=${workspace}
ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"
RUN npm install -g pnpm

FROM base as builder
WORKDIR /app
COPY . .
RUN pnpm install -g turbo
RUN npx turbo prune --scope=${WORKSPACE} --docker

FROM base AS installer
WORKDIR /app
COPY .npmrc .npmrc
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=builder /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml
RUN npx pnpm install
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json

FROM base as runner
WORKDIR /app
COPY --from=installer /app .