FROM node:lts-alpine

ARG service

WORKDIR /usr/app

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY tsconfig.json tsconfig.json

COPY @lute @lute
COPY services/${service} services/${service}


RUN npm run install-workspace
RUN npm install -g nodemon

WORKDIR /usr/app/services/${service}

CMD ["npx", "nodemon",  "src/index.ts"]