version: '3'

volumes:
  prometheus_data: {}

services:
  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    build: ./prometheus
    volumes:
      - prometheus_data:/prometheus
    environment:
      - ENV
      - PROM_NODE_EXPORTER_TARGET
      - PROM_LUTE_TARGET
      - PROM_REMOTE_WRITE_HOST
      - PROM_REMOTE_WRITE_USERNAME
      - PROM_REMOTE_WRITE_PASSWORD
    ports:
     - 9090:9090
  
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        workspace: dashboard
        next_lute_service_url: ${NEXT_PUBLIC_LUTE_SERVER_URL}
    ports:
      - ${DASHBOARD_PORT}:80
    restart: always
    env_file:
      - .env
    environment:
      - PORT=80
      - NEW_RELIC_LICENSE_KEY=${MY_NEWRELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=dashboard
      
  lute:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        workspace: lute
    ports:
      - ${SERVER_PORT}:80
      - 9229:9229
    restart: always
    env_file:
      - .env
    environment:
      - NEW_RELIC_LICENSE_KEY=${MY_NEWRELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=lute
