global:
  scrape_interval: 5s
      
scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
      labels:
        group: {{ getenv "ENV" }}

  - job_name: "node"
    static_configs:
    - targets: ['{{ getenv "PROM_NODE_EXPORTER_TARGET" }}']
      labels:
        group: {{ getenv "ENV" }}

  - job_name: "lute"
    static_configs:
    - targets: ['{{ getenv "PROM_LUTE_TARGET" }}']
      labels:
        group: {{ getenv "ENV" }}

remote_write:
  - url: {{ getenv "PROM_REMOTE_WRITE_HOST" }}
    basic_auth:
      username: {{ getenv "PROM_REMOTE_WRITE_USERNAME" }}
      password: {{ getenv "PROM_REMOTE_WRITE_PASSWORD" }}