global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'lute'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['lute:80']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']